version: 0.2

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm run build
  post_build:
    commands:
        - aws s3 sync --delete --sse AES256 --acl private --only-show-errors dist/ s3://entu-webapp
