version: 0.2

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - cp ./assets/robots.txt ./build/robots.txt
            - cp ./assets/img/favicon.ico ./build/favicon.ico

artifacts:
    files:
        - '**/*'
    discard-paths: no
    base-directory: build
