version: 0.2

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - aws s3 sync --sse AES256 --acl private --only-show-errors --cache-control max-age=2592000 dist/ s3://entu-webapp
            - aws s3 cp --sse AES256 --acl private --only-show-errors --cache-control max-age=300 dist/index.html s3://entu-webapp/index.html
            - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths /\*
