version: 0.2

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - cp ./src/assets/robots.txt ./dist/robots.txt
            - cp ./src/assets/favicon.ico ./dist/favicon.ico

artifacts:
    files:
        - '**/*'
    discard-paths: no
    base-directory: dist
